### ISSUE TITLE
Placeholder API support

### ISSUE THREAD

**Issue by SirFancyBacon** [Jacob-Butch/BookMenus#1]
Hello,
I'd like to use your plugin to make a "Quest Log" of sorts.
Currently i am using Placeholder API to run some Javascript that swaps out what is being shown based on some checks within customNPCs.

If you do look into my request; use the plugin from here as the official build doesn't seem to work
https://github.com/randombyte-developer/PlaceholderAPI/releases/

this build has no changes and is just compiled correctly.

**Comment by Jacob-Butch** [comment]
PlaceholderAPI support has been implemented with the newest release! :D
