### ISSUE TITLE
[BUG] Permissions are not executed correctly

### ISSUE THREAD

**Issue by SirFancyBacon** [Jacob-Butch/BookMenus#2]
when attempting to use LuckPerms permissions setting `bookmenus.command.book.open` to true results in the command `book open` to fail.

when setting `bookmenus.command.book` to true, the commands work fine; however anyone can now save and overwrite books.
this appears to defeat the purpose of permissions and thus appears to be undesired.

Can this issue be resolved?

**Comment by Jacob-Butch** [comment]
I will look into this now, sorry for taking so long to get back to you.
